name: CI/CD Pipeline Workflow

on:
  push

permissions:
  security-events: write

jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting CI/CD workflow. status ${{ job.status }}"

      - name: Check out repo code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Run TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          # outputFile: trufflehog-results.json

      - name: Exit on secrets detected
        if: failure()
        run: |
          echo "Saw a secret" 
          exit 1

      # - name: SonarQube Scan
      #   uses: SonarSource/sonarqube-scan-action@v4 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      #   with:
      #     projectBaseDir: .
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONARQUBE_API_KEY }}

      - name: Install dependencies
        run: npm ci
      
      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      - run: echo "Pipeline run successfully. Have a great day! status ${{ job.status }}"