name: CI/CD Pipeline Workflow

on:
  push

jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting CI/CD workflow. status ${{ job.status }}"

      - name: Check out repo code
        uses: actions/checkout@v4
      
      - name: Install TruffleHog
        run: |
          pip install trufflehog

      - name: Run TruffleHog
        run: |
          trufflehog git file://. \
            # --fail \
            # --only-verified \
            --branch main \
            --json \
            > trufflehog-results.json || echo "Secrets detected!"

      - name: Upload TruffleHog Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-results.json

      - name: Install dependencies
        run: npm ci
      
      - run: echo "Pipeline run successfully. Have a great day! status ${{ job.status }}"